version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: default
      POSTGRES_HOST: localhost
    restart: unless-stopped